// Generated by CoffeeScript 1.11.1
var app, router;

import Vue from 'vue';

import VueRouter from 'vue-router';

import Vuex from 'vuex';

import App from './App';

import VueMdl from 'vue-mdl';

require('assets/material-design-lite.scss');

Vue.use(VueRouter);

Vue.use(Vuex);

Vue.use(VueMdl);

import {
  routes
} from './routes';

router = new VueRouter({
  routes: routes
});

app = new Vue({
  router: router,
  template: '<App/>',
  components: {
    App: App
  }
}).$mount('#app');
