// Generated by CoffeeScript 1.11.1
import Vue from 'vue';

import VueRouter from 'vue-router';

import Vuex from 'vuex';

import App from './App';

new Vue({
  el: '#app',
  template: '<App/>',
  components: {
    App: App
  }
});

Vue.use(VueRouter);

Vue.use(Vuex);
